# vim: set sw=4 ts=4 et :
imports:
    - php

filter:
    excluded_paths:
        - "test/"

tools:
    external_code_coverage: true

    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    tests:
        override:
            - phpcs-run
